### ISSUE TITLE
Is it possible to clone all issues assigned to me (and/or that I'm watching)?

### ISSUE THREAD

**Issue by waynew** [coddingtonbear/jirafs#33]
The title says it all. I haven't been able to find anything in the documentation. I just want to be able to do something like `jirafs clone --mine` or something, and then it pulls down all issues assigned to me.

It might also be nice to have something like `jirafs --prune` that would remove directories from issues I'm no longer assigned to.

**Comment by coddingtonbear** [comment]
Possible -- yes; implemented -- no.  Re `--prune`, I've been thinking about a command that would run another command based upon the contents of an arbitrary field, and it sounds like `--prune` could just be a special case of that.  Feel free to implement it and file a pull request.

Cheers!
