### ISSUE TITLE
Option to never ask to save password

### ISSUE THREAD

**Issue by commonquail** [coddingtonbear/jirafs#43]
If I don't want to save my password, the overhead of being asked every time I interact with JIRA gets irritating. Please allow some way of disabling this question.

Relevant line: https://github.com/coddingtonbear/jirafs/blob/8046e19868c340daa0e540aea8a0b815d07b6c7e/jirafs/utils.py#L209

**Comment by coddingtonbear** [comment]
I've just added this as a feature as part of 1.17.0.  Check out [this little bit of the documentation](http://jirafs.readthedocs.org/en/latest/configuration.html#disabling-save-jira-password-prompt) for instructions on disabling the save prompt.

Cheers!
