### ISSUE TITLE
How to register new command?

### ISSUE THREAD

**Issue by mcepl** [coddingtonbear/jirafs#51]
Hi, I try to write a command plugin as a reaction to #33, but I stumbled even on the first step. When I create this https://gitlab.com/mcepl/jirafs_mine/ and install on my system via `python3 setup.py develop --user`, and then run:

```
$ jirafs help
```

my new command (``list_tickets``) is not displayed. ``jirafs`` has been installed from the openSUSE package so the binary is in ``/usr/bin/jirafs`` and its libraries in ``/usr/lib/python3.7/site-packages/jirafs/``. My plugin is registered in ``/home/matej/.local/lib/python3.7/site-packages/jirafs-mine.egg-link`` (with content a directory containing whole plugin project).

What I am missing?

**Comment by coddingtonbear** [comment]
Ooo; hrm -- I'm sorry to say that really, the error messages around this should be better, so I'll be posting a fix for that in a few minutes, but the gist of the problem is this: your plugin is registered in your `setup.py` set up to be a `jirafs_plugin` (all of which must be a subclass of `jirafs.plugin.Plugin`), but the actual plugin that you've written is instead a subclass of `jirafs.plugin.CommandPlugin`, and those need to be registered under a different key in your `setup.py` -- `jirafs_commands`.

Hopefully that helps!

**Comment by coddingtonbear** [comment]
Log messages improved in 1.17.4.

**Comment by mcepl** [comment]
Thanks, that helped. Somehow. However, your example is obviously outdated:

```
SLE-5641@stitny$ jirafs list_tickets
Traceback (most recent call last):
  File "/usr/bin/jirafs", line 11, in <module>
    load_entry_point('jirafs==1.17.3', 'console_scripts', 'jirafs')()
  File "/usr/lib/python3.7/site-packages/jirafs/cmdline.py", line 108, in main
    extra, jira=jira, path=args.folder, command_name=command_name
  File "/usr/lib/python3.7/site-packages/jirafs/plugin.py", line 266, in execute_command
    cmd.handle(**kwargs)
  File "/home/matej/archiv/2019/SUSE/projekty/jirafs_mine/list_commands.py", line 13, in handle
    return self.cmd(folder, *self.git_arguments)
  File "/usr/lib/python3.7/site-packages/jirafs/plugin.py", line 307, in cmd
    self.main(*args, **kwargs)
  File "/home/matej/archiv/2019/SUSE/projekty/jirafs_mine/list_commands.py", line 21, in main
    result = folder.run_git_command(*git_arguments)
TypeError: run_git_command() missing 1 required positional argument: 'command'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

SLE-5641@stitny$
```

What in the world has IPython to do with this script? Does jirafs uses IPython somewhere?

**Comment by coddingtonbear** [comment]
The problem you're encountering from the example is that you need to provide at least one command to hand off to git.

Ipython is a transitive requirement via the JIRA dependency used here.

**Comment by coddingtonbear** [comment]
Incidentally -- if you'd like to chat 1:1 about this kind of thing, feel free to reach out on the gitter channel: https://gitter.im/coddingtonbear/jirafs
