### ISSUE TITLE
comment.author.name field not present

### ISSUE THREAD

**Issue by mattboehm** [coddingtonbear/jirafs#63]
I just installed jirafs via pip, but when I tried cloning an issue from my company's Atlassian Cloud instance, I got a stack trace.

The root cause appears to be that comment.author does not have a name field. However, it does appear to have a displayName field, so I quickly patched things by updating fetch.py:126 to the following:

    comment.author.displayName if hasattr(comment.author, "displayName") else comment.author.name,

I haven't yet looked into whether this discrepancy is due to a change in the Jira client code or if it's a quirk in the Jira instance I'm connecting through, but thought I'd raise the issue.

Please let me know if you'd like any additional info from me. Thanks!

**Comment by coddingtonbear** [comment]
Apparently this is rooted in some GDPR changes: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/ --- I'll look into adding that as a fallback.

Thanks for the report!

**Comment by coddingtonbear** [comment]
Fixed as part of 2.2.1
